// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file protos/disk.proto (package fastifytemplate, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file protos/disk.proto.
 */
export const file_protos_disk: GenFile = /*@__PURE__*/
  fileDesc("ChFwcm90b3MvZGlzay5wcm90bxIPZmFzdGlmeXRlbXBsYXRlIkgKCURpc2tTdGF0ZRITCgt0b3RhbF9zcGFjZRgBIAEoBBISCgp1c2VkX3NwYWNlGAIgASgEEhIKCmZyZWVfc3BhY2UYAyABKARiBnByb3RvMw");

/**
 * @generated from message fastifytemplate.DiskState
 */
export type DiskState = Message<"fastifytemplate.DiskState"> & {
  /**
   * Total disk space in bytes
   *
   * @generated from field: uint64 total_space = 1;
   */
  totalSpace: bigint;

  /**
   * Used disk space in bytes
   *
   * @generated from field: uint64 used_space = 2;
   */
  usedSpace: bigint;

  /**
   * Free disk space in bytes
   *
   * @generated from field: uint64 free_space = 3;
   */
  freeSpace: bigint;
};

/**
 * Describes the message fastifytemplate.DiskState.
 * Use `create(DiskStateSchema)` to create a new message.
 */
export const DiskStateSchema: GenMessage<DiskState> = /*@__PURE__*/
  messageDesc(file_protos_disk, 0);

