// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file protos/fuel.proto (package fastifytemplate, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file protos/fuel.proto.
 */
export const file_protos_fuel: GenFile = /*@__PURE__*/
  fileDesc("ChFwcm90b3MvZnVlbC5wcm90bxIPZmFzdGlmeXRlbXBsYXRlIj4KCUZ1ZWxTdGF0ZRISCgpmdWVsX2xldmVsGAEgASgBEh0KFWZ1ZWxfY29uc3VtcHRpb25fcmF0ZRgCIAEoAWIGcHJvdG8z");

/**
 * @generated from message fastifytemplate.FuelState
 */
export type FuelState = Message<"fastifytemplate.FuelState"> & {
  /**
   * Fuel level in liters
   *
   * @generated from field: double fuel_level = 1;
   */
  fuelLevel: number;

  /**
   * Fuel consumption rate in liters per hour
   *
   * @generated from field: double fuel_consumption_rate = 2;
   */
  fuelConsumptionRate: number;
};

/**
 * Describes the message fastifytemplate.FuelState.
 * Use `create(FuelStateSchema)` to create a new message.
 */
export const FuelStateSchema: GenMessage<FuelState> = /*@__PURE__*/
  messageDesc(file_protos_fuel, 0);

