// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file protos/geopose.proto (package fastifytemplate, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file protos/geopose.proto.
 */
export const file_protos_geopose: GenFile = /*@__PURE__*/
  fileDesc("ChRwcm90b3MvZ2VvcG9zZS5wcm90bxIPZmFzdGlmeXRlbXBsYXRlIkAKB0dlb1Bvc2USEAoIbGF0aXR1ZGUYASABKAESEQoJbG9uZ2l0dWRlGAIgASgBEhAKCGFsdGl0dWRlGAMgASgBYgZwcm90bzM");

/**
 * @generated from message fastifytemplate.GeoPose
 */
export type GeoPose = Message<"fastifytemplate.GeoPose"> & {
  /**
   * Latitude in degrees
   *
   * @generated from field: double latitude = 1;
   */
  latitude: number;

  /**
   * Longitude in degrees
   *
   * @generated from field: double longitude = 2;
   */
  longitude: number;

  /**
   * Altitude in meters
   *
   * @generated from field: double altitude = 3;
   */
  altitude: number;
};

/**
 * Describes the message fastifytemplate.GeoPose.
 * Use `create(GeoPoseSchema)` to create a new message.
 */
export const GeoPoseSchema: GenMessage<GeoPose> = /*@__PURE__*/
  messageDesc(file_protos_geopose, 0);

